APPIO_MOD_DIR := $(USERMOD_DIR)
APPIO_LIB_DIR := $(APPIO_MOD_DIR)/../../../lib/app_i2c
SRC_USERMOD += $(APPIO_MOD_DIR)/modappio.c
SRC_USERMOD += $(APPIO_LIB_DIR)/app_i2c.c
CFLAGS_USERMOD += -I$(APPIO_LIB_DIR)
